baseURL: "https://wcsukee.netlify.app/"
title: West Coast Shape Surfboard
description: Site Tagline
relativeURLs: true

menu:
  main:
  - name: Home
    url: '/'
    weight: 1
  - name: About
    url: 'about/'
    weight: 2
  - name: Surfboards
    url: /surfboards
    weight: 3
  - name: Services
    url: 'services/'
    weight: 4
  - name: Contact
    url: 'contact/'
    weight: 5

params:
    name: 'West Coast Shape Surfboard'
    usebasin: 'https://usebasin.com/f/244688722c09' #endpoint for forms
    googlemap: '' # Map code of Google
    gtm: 'GTM-T7ZN93Zam'
    hours:
        hour1en: 'Mon to Fri - 9:00-17:00' #Footer Hours Line #1
        hour2en: 'Sat - Closed' #Footer Hours Line #2
        hour3en: 'Sun - Closed' #Footer Hours Line #3
    social:
        facebook: 'https://www.facebook.com/'
        twitter: ''
        pinterest: ''
        instagram: ''
        linkedin: 'https://ca.linkedin.com/'
    schema:
        type: ProfessionalService
        priceRange: $$$
        reservation: 'false'
        openinghour: 'Mo-Fr 9:00-17:00'
        logo: "img/logo.jpg"
        logo_footer: "img/logo_transparent.png"
        image: "img/og.jpg"
        address: TBD
        address2: TBD
        city: Ucluelet
        region: BC
        country: Canada
        postalcode: V0R 3A0
        phone: +1-250-266-7859
        email: info@wcsukee.com

enableRobotsTXT: true
disableAliases: true
disableKinds:
  - taxonomy
  - taxonomyTerm

sitemap:
  changefreq: monthly
  filename: sitemap.xml

imaging:
  resampleFilter: box
  quality: 85
  anchor: smart